In [2]:
import numpy as np

In [2]:
numpy_arr = np.array([1, 2, 0, 9, 6, 7], np.int32)

In [3]:
arr = np.array([[1, 3, 56], [3, 5, 0], [3, 54, 56], [0, 890, 234908]], np.int64)

In [4]:
print(arr)
print(arr[3, 0])     # acessing elements like this bro
print(arr.shape)      # this show the number of row i.e. 4 and 3 are the column
print(arr.dtype)

[[     1      3     56]
 [     3      5      0]
 [     3     54     56]
 [     0    890 234908]]
0
(4, 3)
int64


In [5]:
arrays = np.array([1, 2, 4, 5], np.int8)

In [6]:
print(numpy_arr[3])

print(arrays)
print(numpy_arr.shape)
print(arrays.shape)
print(arrays.dtype)              # giving us the data type

9
[1 2 4 5]
(6,)
(4,)
int8


In [7]:
bro_arr = np.array([["abhinav", "kumar", "Choudhary"], ["to", "kese", "Hai", "aap", "log"]], dtype=object)

In [8]:
print(bro_arr.shape)
print(bro_arr.dtype)


(2,)
object


In [9]:
bro_arr = list(bro_arr)
print(bro_arr)
print(type(bro_arr))
print(bro_arr[1][0])    # here we have to act as simple as list are

[['abhinav', 'kumar', 'Choudhary'], ['to', 'kese', 'Hai', 'aap', 'log']]
<class 'list'>
to


In [10]:
print(arrays)
print(arr)

[1 2 4 5]
[[     1      3     56]
 [     3      5      0]
 [     3     54     56]
 [     0    890 234908]]


In [11]:
arrays[0] = 9
arr[1, 2] = 90

In [12]:
print(arrays)
print(arr)

[9 2 4 5]
[[     1      3     56]
 [     3      5     90]
 [     3     54     56]
 [     0    890 234908]]


### Array Creation : Conversion from other Python structures (e.g., lists, tuples)

In [13]:
listarray = np.array([[9, 3, 0], [2, 97, -82], [-82, -90, 102], [1, 90, 34]])

In [14]:
print(listarray)
print(listarray.size)
print(listarray.shape)
print(listarray.dtype)

[[  9   3   0]
 [  2  97 -82]
 [-82 -90 102]
 [  1  90  34]]
12
(4, 3)
int32


In [15]:
tuplearray = np.array(((2, 0), (-9, 32), (324, -324)))

In [16]:
print(tuplearray)
print(tuplearray.shape)
print(tuplearray.dtype)
print(tuplearray.size)

[[   2    0]
 [  -9   32]
 [ 324 -324]]
(3, 2)
int32
6


### Array Creation : Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [17]:
# zeros function in numpy

zeros = np.zeros((3, 5))     # this will create a array of zeros with 3 rows and 5 column, indirectly this is shape

In [18]:
print(zeros)
print(zeros.shape)
print(zeros.dtype)
print(zeros.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)
float64
15


In [19]:
# arange function in numpy

rng = np.arange(100, 10, -10)     # this is also same as range() in python return the array

In [20]:
print(rng)
print(rng.shape)
print(rng.dtype)
print(rng.size)

[100  90  80  70  60  50  40  30  20]
(9,)
int32
9


In [21]:
# linspace function in numpy

linspace = np.linspace(100, 1000, 50)     # this will return a array of equal 50 space between 100 to 1000

In [22]:
print(linspace)
print(linspace.shape)
print(linspace.dtype)
print(linspace.size)


[ 100.          118.36734694  136.73469388  155.10204082  173.46938776
  191.83673469  210.20408163  228.57142857  246.93877551  265.30612245
  283.67346939  302.04081633  320.40816327  338.7755102   357.14285714
  375.51020408  393.87755102  412.24489796  430.6122449   448.97959184
  467.34693878  485.71428571  504.08163265  522.44897959  540.81632653
  559.18367347  577.55102041  595.91836735  614.28571429  632.65306122
  651.02040816  669.3877551   687.75510204  706.12244898  724.48979592
  742.85714286  761.2244898   779.59183673  797.95918367  816.32653061
  834.69387755  853.06122449  871.42857143  889.79591837  908.16326531
  926.53061224  944.89795918  963.26530612  981.63265306 1000.        ]
(50,)
float64
50


In [23]:
# Empty function in python

empty = np.empty((5, 10))      # this return the the array of sape (5, 10) 5 rows 10 column and in that all the random numbers will there present

In [24]:
print(empty)
print(empty.shape)   # this is also (5, 10)
print(empty.dtype)
print(empty.size)    # total size of all the elements

[[ 100.          118.36734694  136.73469388  155.10204082  173.46938776
   191.83673469  210.20408163  228.57142857  246.93877551  265.30612245]
 [ 283.67346939  302.04081633  320.40816327  338.7755102   357.14285714
   375.51020408  393.87755102  412.24489796  430.6122449   448.97959184]
 [ 467.34693878  485.71428571  504.08163265  522.44897959  540.81632653
   559.18367347  577.55102041  595.91836735  614.28571429  632.65306122]
 [ 651.02040816  669.3877551   687.75510204  706.12244898  724.48979592
   742.85714286  761.2244898   779.59183673  797.95918367  816.32653061]
 [ 834.69387755  853.06122449  871.42857143  889.79591837  908.16326531
   926.53061224  944.89795918  963.26530612  981.63265306 1000.        ]]
(5, 10)
float64
50


In [25]:
# empty like function in numpyt

empty_like = np.empty_like(linspace)      # this takes any array and make the copy of it, now in this we can change or parsed do any thing which we want


In [26]:
print(empty_like)
print(empty_like.shape)
print(empty_like.dtype)
print(empty_like.size)

[ 100.          118.36734694  136.73469388  155.10204082  173.46938776
  191.83673469  210.20408163  228.57142857  246.93877551  265.30612245
  283.67346939  302.04081633  320.40816327  338.7755102   357.14285714
  375.51020408  393.87755102  412.24489796  430.6122449   448.97959184
  467.34693878  485.71428571  504.08163265  522.44897959  540.81632653
  559.18367347  577.55102041  595.91836735  614.28571429  632.65306122
  651.02040816  669.3877551   687.75510204  706.12244898  724.48979592
  742.85714286  761.2244898   779.59183673  797.95918367  816.32653061
  834.69387755  853.06122449  871.42857143  889.79591837  908.16326531
  926.53061224  944.89795918  963.26530612  981.63265306 1000.        ]
(50,)
float64
50


In [27]:
# Identity function in numpy

identity = np.identity(50)    # this return the identity metrix array of (50, 50) shape

In [28]:
print(identity)
print(identity.shape)
print(identity.dtype)
print(identity.size)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(50, 50)
float64
2500


In [29]:
# reshape function in numpy

arr = np.arange(100)     # this is one dimentional array okay just for example
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [30]:
arr = arr.reshape(20, 5)         # now I suppose to return the reshaped of the array as the there shape in argument

# note : the element shoud be fit i.e. 20*5 = len(arr) other wise it will through the error
# try to put arr.reshape(30, 20)    # this will definatly thorw an error

In [31]:
print(arr)            # note that even you can reshpae it while creating it
print(arr.shape)     # as per the reshape argument

# arr = np.arange(100).reshape(20, 5)     # samjh aa raha hai bhai

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
(20, 5)


In [32]:
# ravel() fucntion in numpy

arr = arr.ravel()     # this return the array in just one dimentional

In [33]:
print(arr)
print(arr.shape)

# arr = np.arane(100).reshape(20, 50).ravel().reshape(20, 5)      # here also the python logic is same bro

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


**Important topic Numpy Axis :**

In [34]:
x = [[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [35]:
ax = np.array(x)

In [36]:
print(ax)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [37]:
print(ax.sum(axis=0))      # 0 axis is column
print(ax.sum(axis=1))      # 1 axis is row  

# return the sum of axis 0 = 11 + 44 + 77 = 132, 22 + 55 + 88 = 165, 33 +66 +99 = 198 
# now all the sum are put in the array as per there position 
# [132, 165, 198]


[132 165 198]
[ 66 165 264]


In [38]:
# .T method is return the Transpose array      i.e. axis 0 to axis 1 and axis 1 to axis 0
print(ax.T)     # column to row and row to column

[[11 44 77]
 [22 55 88]
 [33 66 99]]


In [39]:
# .flat method is retuning the iterator which can easily iterate over for loop or by next() function or by __next__() method
iterarr = ax.flat

print(iterarr.__next__())
print(next(iterarr))

for iterm in iterarr:
    print(iterm)


11
22
33
44
55
66
77
88
99


In [40]:
# this will normal for loop

for i in ax:
    print(*i)
    print(i)

11 22 33
[11 22 33]
44 55 66
[44 55 66]
77 88 99
[77 88 99]


In [41]:
print(ax.ndim)

2


In [42]:
print(ax.nbytes)

36


In [43]:
print(ax.size)

9


In [44]:
print(ax.shape)

(3, 3)


In [45]:
one = np.array([1, 9, 3, 5, 7, 8, 2, 0])

In [46]:
print(one.argmax())     # argument's maximus : the maximum value's index
print(one.argmin())     # minimum argument : the minimum value's index
one.argsort()           # sort the value but return the list of index in sorted form just like smallest value is 0 so it will return a list[0]= 7 cause 0 is on 7th index bro

# this was on 1d array

1
7


array([7, 0, 6, 2, 3, 4, 5, 1], dtype=int64)

In [47]:
ax

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [48]:
ax.argmin()      # first it had converted or assumed as a 1d list and return its index, 11's index is 0 and 11 is smalled number here

0

In [49]:
ax.argmax()     # convert in 1d array then return the index of maximum value which is 99 and its index will be 8

8

In [50]:
ax.argmax(axis=0)    # 0 axis se dekh kr chalo in ax[1] , 2nd index is heighest in ax[2], 2nd index is heighest and in ax[3] 2nd index is hieghest



array([2, 2, 2], dtype=int64)

In [51]:
ax.argmin(axis=1)     # samjh rahe ho, samjh rahe ho n

array([0, 0, 0], dtype=int64)

In [52]:
ax.argsort()     # gaving the index yar to all the element in sorted form

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [53]:
example = np.array([[9, 3, 3, 0], [3, 5, 7, 2], [3, 6, 1, 0]], np.int32)
example

array([[9, 3, 3, 0],
       [3, 5, 7, 2],
       [3, 6, 1, 0]])

In [54]:
example.argsort()    # dekh rahe ho, sort kerke de diya na, esse hum axis ke sath bhi kr sakte hai yad rakhna

# axis=1 by default, samjh rahe ho balak

array([[3, 1, 2, 0],
       [3, 0, 1, 2],
       [3, 2, 0, 1]], dtype=int64)

In [55]:
example.argsort(axis=0)    # here the all elements are on its own place, but assuming the axis 0 we are getting the sorted form

array([[1, 0, 2, 0],
       [2, 1, 0, 2],
       [0, 2, 1, 1]], dtype=int64)

In [56]:
example.ravel()

array([9, 3, 3, 0, 3, 5, 7, 2, 3, 6, 1, 0])

In [58]:
example.reshape(3, 4)

array([[9, 3, 3, 0],
       [3, 5, 7, 2],
       [3, 6, 1, 0]])

In [5]:
abhinav = np.random.rand(5, 3, 5, 8)

In [6]:
abhinav

array([[[[0.16445296, 0.11294137, 0.60955476, 0.88634158, 0.43963731,
          0.49963254, 0.89445963, 0.18512882],
         [0.01014466, 0.09010101, 0.35961092, 0.19036107, 0.67094363,
          0.70081582, 0.94005827, 0.83885817],
         [0.81277335, 0.621121  , 0.11540302, 0.73680052, 0.01553957,
          0.70650928, 0.1101616 , 0.98487246],
         [0.05441426, 0.3631649 , 0.7261117 , 0.95708426, 0.85427412,
          0.70360771, 0.84493964, 0.3773344 ],
         [0.06958051, 0.83728012, 0.05150438, 0.211901  , 0.35801518,
          0.85203494, 0.14558761, 0.42370164]],

        [[0.04726284, 0.20860545, 0.76300986, 0.94089662, 0.1303792 ,
          0.11628101, 0.28438971, 0.50781344],
         [0.77169706, 0.08303018, 0.03957199, 0.47708598, 0.45750001,
          0.49152843, 0.93015332, 0.31820941],
         [0.5922991 , 0.9508116 , 0.73618171, 0.58034949, 0.15549215,
          0.58217038, 0.68844396, 0.32666201],
         [0.74055303, 0.19213433, 0.15200879, 0.9322308 , 0.86

## ***Operators using Numpy, Mathematically Operations and all***